UserParameter=recyclebin.size.lld,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Zabbix\recyclebinsizeW.ps1" --lld
UserParameter=recyclebin.size.user[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Zabbix\recyclebinsizeW.ps1" --user "$1"
